export type Program = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  outcome: string;
  length: string;
  price: string;
  priceEnv?: string;
  free?: boolean;
  inquiryOnly?: boolean;
  lessons: string[];
};

export const programs: Program[] = [
  {
    slug: "calmer-family-week",
    title: "5 Simple Changes for a Calmer Family Week",
    eyebrow: "Free guide",
    description: "A gentle seven-day starting point for overwhelmed families who need simpler rhythms.",
    outcome: "Create calmer mornings, easier transitions, and a more peaceful bedtime routine.",
    length: "7 days",
    price: "Free",
    free: true,
    lessons: ["One small change each day", "Family calm checklist", "Morning and evening routine prompts"],
  },
  {
    slug: "calmer-family-reset",
    title: "Calm Home, Connected Family",
    eyebrow: "Family wellness",
    description: "Practical routines, whole-food foundations, and stress-lowering habits for busy homes.",
    outcome: "Move from survival mode toward a home rhythm your family can actually maintain.",
    length: "6 weeks",
    price: "$49",
    priceEnv: "STRIPE_PRICE_CALMER_FAMILY",
    lessons: ["Calm-home assessment", "Simple routines", "Meal rhythm", "Weekly family reset"],
  },
  {
    slug: "clean-eating-made-simple",
    title: "Clean Eating Health Coaching Program",
    eyebrow: "Nutrition",
    description: "A realistic introduction to reducing ultra-processed foods without chasing perfection.",
    outcome: "Build confidence reading labels, planning meals, and making approachable food swaps.",
    length: "Self-paced",
    price: "$59",
    priceEnv: "STRIPE_PRICE_CLEAN_EATING",
    lessons: ["Pantry refresh", "Label-reading guide", "Meal recipes", "Shopping system"],
  },
  {
    slug: "adhd-parent-roadmap",
    title: "Calm & Capable Kids",
    eyebrow: "Kids & ADHD",
    description: "Strength-based coaching education for families building supportive routines for a child with ADHD.",
    outcome: "Support calmer routines, emotional regulation, healthy habits, confidence, and independence.",
    length: "8 weeks",
    price: "$97",
    priceEnv: "STRIPE_PRICE_ADHD_PARENTS",
    lessons: ["Strength-based planning", "Sensory-friendly routines", "Food and sleep foundations", "Parent reset tools"],
  },
  {
    slug: "family-wellness-reset",
    title: "Calm Home, Connected Family",
    eyebrow: "ADHD family support",
    description: "The complete family coaching experience for calmer rhythms, emotional connection, and sustainable household habits.",
    outcome: "Create a shared family plan for routines, nourishment, emotional regulation, and connection.",
    length: "12 weeks",
    price: "$147",
    priceEnv: "STRIPE_PRICE_FAMILY_RESET",
    lessons: ["Family wellness vision", "Weekly meal rhythm", "Movement and outdoor time", "Home organization"],
  },
  {
    slug: "focused-flourishing",
    title: "Focused & Flourishing",
    eyebrow: "Adult ADHD",
    description: "Practical coaching support for adults with ADHD who want less overwhelm and more workable routines.",
    outcome: "Build sustainable systems for focus, time, energy, nourishment, and everyday responsibilities.",
    length: "8 weeks",
    price: "Pricing available",
    inquiryOnly: true,
    lessons: ["Understanding the ADHD brain", "Nervous-system care", "Time and routine support", "Nutrition and energy habits"],
  },
  {
    slug: "strong-nourished-mama",
    title: "Strong & Nourished Mama",
    eyebrow: "Busy moms",
    description: "A whole-person wellness program for busy moms building strength, energy, and sustainable nourishment habits.",
    outcome: "Create realistic food, movement, and stress-supportive habits that fit a full family schedule.",
    length: "12 weeks",
    price: "Pricing available",
    inquiryOnly: true,
    lessons: ["Reset and foundations", "Balanced nutrition", "Meal-planning support", "Stress and eating awareness"],
  },
  {
    slug: "rooted-renewed",
    title: "Rooted & Renewed",
    eyebrow: "Women over 40",
    description: "Supportive lifestyle coaching for women over 40 focused on nourishment, movement, sleep, and steady habits.",
    outcome: "Build a sustainable wellness rhythm that supports energy, strength, rest, and healthy weight goals.",
    length: "12 weeks",
    price: "Pricing available",
    inquiryOnly: true,
    lessons: ["Resetting the foundations", "Balanced meals", "Strength and movement", "Sleep and stress support"],
  },
  {
    slug: "strong-roots",
    title: "Strong Roots",
    eyebrow: "Men over 40",
    description: "A practical wellness program for men over 40 who want more energy, strength, and consistent daily habits.",
    outcome: "Create realistic routines for nourishment, movement, rest, and long-term strength.",
    length: "12 weeks",
    price: "Pricing available",
    inquiryOnly: true,
    lessons: ["Resetting the basics", "High-protein meal ideas", "Strength-supportive habits", "Rest and stress support"],
  },
  {
    slug: "steady-strong",
    title: "Steady & Strong",
    eyebrow: "Adults over 60",
    description: "Lifestyle coaching for adults over 60 managing insulin resistance alongside care from their medical team.",
    outcome: "Build steady habits around balanced meals, gentle movement, energy, and healthy aging.",
    length: "12 weeks",
    price: "Pricing available",
    inquiryOnly: true,
    lessons: ["Resetting the foundations", "Blood-sugar balance education", "Gentle movement", "Healthy-aging routines"],
  },
  {
    slug: "rooted-restored",
    title: "Rooted & Restored",
    eyebrow: "Emotional wellness",
    description: "Gentle lifestyle coaching for stress, overwhelm, and emotional wellness alongside licensed mental-health care when needed.",
    outcome: "Create calming daily practices that support nourishment, sleep, boundaries, and emotional well-being.",
    length: "8 weeks",
    price: "Pricing available",
    inquiryOnly: true,
    lessons: ["Safety and stabilization", "Nervous-system care", "Sleep and nourishment", "Healthy boundaries"],
  },
  {
    slug: "garden-to-wellness",
    title: "Garden to Wellness",
    eyebrow: "Garden skills",
    description: "Use simple gardening and food-growing projects to build confidence, nourishment, and connection.",
    outcome: "Start growing food at your own pace—even with limited space or experience.",
    length: "6 weeks",
    price: "$79",
    priceEnv: "STRIPE_PRICE_GARDEN_WELLNESS",
    lessons: ["Choose your growing method", "Hydroponic basics", "Family garden jobs", "Harvest-to-table ideas"],
  },
  {
    slug: "red-light-foundations",
    title: "Red Light Therapy Foundations",
    eyebrow: "Wellness education",
    description: "An educational guide to common red-light routines, device questions, and safety conversations.",
    outcome: "Understand the basics and prepare informed questions for your licensed healthcare professional.",
    length: "Self-paced",
    price: "$39",
    priceEnv: "STRIPE_PRICE_RED_LIGHT",
    lessons: ["How red light is discussed", "Device basics", "Routine tracker", "Safety questions"],
  },
  {
    slug: "rooted-radiant",
    title: "Rooted & Radiant",
    eyebrow: "Stress + skin wellness",
    description: "A six-week wellness reset combining stress-management habits, nourishing food, sleep, movement, gentle skin care, and a 15-minute red-light routine when that timing matches your device instructions.",
    outcome: "Build a calmer daily rhythm that supports stress management, recovery, and healthier-looking skin without restrictive routines or medical promises.",
    length: "6 weeks",
    price: "$1 launch offer · $98 after October 20, 2026",
    priceEnv: "STRIPE_PRICE_ROOTED_RADIANT_LAUNCH",
    lessons: [
      "Week 1: Calm the Chaos",
      "Week 2: Nourish From Within",
      "Week 3: Create Your Skin-Supportive Routine",
      "Week 4: Sleep & Recovery",
      "Week 5: Move Stress Out of the Body",
      "Week 6: Build Your Soil to Soul Lifestyle",
    ],
  },
];

export function getProgram(slug: string) {
  return programs.find((program) => program.slug === slug);
}
